// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/scrape": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/pipeline": {
    params: {};
  };
  "/settings/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/api/scrape" | "/jobs" | "/pipeline" | "/settings/profile";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/api.scrape.ts": {
    id: "routes/api.scrape";
    page: "/api/scrape";
  };
  "components/app-layout.tsx": {
    id: "components/app-layout";
    page: "/" | "/jobs" | "/pipeline" | "/settings/profile";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
  "routes/pipeline.tsx": {
    id: "routes/pipeline";
    page: "/pipeline";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/api.scrape": typeof import("./app/routes/api.scrape.ts");
  "components/app-layout": typeof import("./app/components/app-layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/jobs": typeof import("./app/routes/jobs.tsx");
  "routes/pipeline": typeof import("./app/routes/pipeline.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};